name: wills_tinder_cat_dog
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  wills_in_memory_database:
    path: ../wills_in_memory_database

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
